project:
  type: website

website:
  title: "Yet Another Wiki"
  back-to-top-navigation: true
  repo-url: https://github.com/Wcarcamo/yet_another_wiki
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: blog.qmd
        text: Yet Another Blog
    right:
      - icon: github
        href: https://github.com/wcarcamo
        aria-label: GitHub

  sidebar:
    - title: "Yet Another Wiki"
      style: "docked"
      contents:
        - index.qmd
        - section: wiki/linux.qmd
          contents:
            - wiki/linux/ssh.qmd
        - section: "Homelab"
          contents: 
            - wiki/homelab/proxmox.qmd
            - wiki/homelab/docker.qmd
            - wiki/homelab/services.qmd
            - wiki/homelab/ansible.qmd
            - wiki/homelab/networking.qmd
        - section: "Programming"
          contents:
            - wiki/programming/python.qmd

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
